### ISSUE TITLE
Questions about betterdiscord support

### ISSUE THREAD

**Issue by Dreaming-Codes** [GooseMod/topaz#2]
Hi, I'm trying to install a plugin which isn't in the popular plugin list and I'm getting an error saying that it couldn't find index.js which is normal since I'm trying to install this https://github.com/ImTheSquid/Tuxphones/blob/main/bd/builds/Tuxphones.plugin.js
Furthermore this plugin requires the ZeresPluginLibrary is support for libs already a thing?

**Comment by CanadaHonk** [comment]
That plugin won't work as it interfaces with native code which isn't possible currently.
